import {useEffect,useMemo,useState} from 'react';
import type {FormEvent,ReactNode} from 'react';
import {supabase} from './lib/supabase';
import type {Bill,Customer,Permission,Profile,Settings} from './types';

const PERMISSIONS:Permission[]=['customers.view','customers.create','customers.edit','customers.delete','billing.view','billing.generate','billing.edit','payments.view','payments.create','employees.view','employees.manage','audit.view'];
const LABELS:Record<Permission,string>={
 'customers.view':'গ্রাহক দেখা','customers.create':'গ্রাহক যোগ','customers.edit':'গ্রাহক সম্পাদনা','customers.delete':'গ্রাহক মুছুন',
 'billing.view':'বিল দেখা','billing.generate':'মাসিক বিল তৈরি','billing.edit':'বিল সম্পাদনা',
 'payments.view':'পেমেন্ট দেখা','payments.create':'পেমেন্ট গ্রহণ','employees.view':'কর্মচারী দেখা','employees.manage':'কর্মচারী/পারমিশন','audit.view':'অডিট লগ'
};
const money=(n:number)=>new Intl.NumberFormat('bn-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(Number(n||0));
const monthLabel=(s:string)=>new Date(s+'T00:00:00').toLocaleDateString('bn-BD',{month:'long',year:'numeric'});
const monthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)};
const can=(profile:Profile|null,permissions:Set<string>,p:Permission)=>profile?.role==='admin'||permissions.has(p);

function Login(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 return <div className="login-page"><div className="login-card"><div className="brand-mark">আরকি</div><h1>আরকি নেটওয়ার্ক</h1><p>মাসিক বিল ম্যানেজমেন্ট সিস্টেম</p><form onSubmit={submit}><label>ইমেইল<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>পাসওয়ার্ড<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'প্রবেশ করা হচ্ছে…':'লগইন'}</button></form><small>প্রথম Admin account Supabase Authentication থেকে তৈরি করুন।</small></div></div>
}
function Shell({profile,permissions,settings,children,onNavigate,page,onSignOut}:{profile:Profile;permissions:Set<string>;settings:Settings|null;children:ReactNode;onNavigate:(p:string)=>void;page:string;onSignOut:()=>void}){
 const items=[['dashboard','ড্যাশবোর্ড','▦',true],['customers','গ্রাহক','◉',can(profile,permissions,'customers.view')],['bills','মাসিক বিল','৳',can(profile,permissions,'billing.view')],['reports','রিপোর্ট','▤',can(profile,permissions,'billing.view')],['employees','কর্মচারী','♙',can(profile,permissions,'employees.view')],['settings','সেটিংস','⚙',profile.role==='admin']];
 return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="logo">আরকি</div><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Billing System</span></div></div><nav>{items.filter(x=>x[3]).map(x=><button key={x[0]} className={page===x[0]?'nav active':'nav'} onClick={()=>onNavigate(x[0])}><i>{x[2]}</i>{x[1]}</button>)}</nav><div className="side-bottom"><div className="user-mini"><div className="avatar">{(profile.full_name||'U').slice(0,1)}</div><div><b>{profile.full_name||'User'}</b><span>{profile.role==='admin'?'Admin':'Employee'}</span></div></div><button className="nav" onClick={onSignOut}><i>↪</i>লগআউট</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{settings?.tagline||'মাসিক বিল ব্যবস্থাপনা'}</span><h2>{items.find(x=>x[0]===page)?.[1]||'ড্যাশবোর্ড'}</h2></div><span className="role-pill">{profile.role}</span></header>{children}</main></div>
}
function Stat({title,value,sub,icon}:{title:string;value:string;sub?:string;icon:string}){return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div></div>}
function Dashboard(){
 const [loading,setLoading]=useState(true);const [stats,setStats]=useState({customers:0,expected:0,collected:0,due:0,paid:0,partial:0});const [recent,setRecent]=useState<any[]>([]);
 useEffect(()=>{(async()=>{setLoading(true);const m=monthStart();const [c,b,p]=await Promise.all([supabase.from('customers').select('id,status',{count:'exact'}),supabase.from('bills').select('amount_due,amount_paid,due_amount,status').eq('billing_month',m),supabase.from('payments').select('id,amount,payment_date,receipt_no,customer_id,customers(name,customer_code)').order('payment_date',{ascending:false}).limit(8)]);const bs=b.data||[];setStats({customers:c.count||0,expected:bs.reduce((a:any,x:any)=>a+Number(x.amount_due),0),collected:bs.reduce((a:any,x:any)=>a+Number(x.amount_paid),0),due:bs.reduce((a:any,x:any)=>a+Number(x.due_amount),0),paid:bs.filter((x:any)=>x.status==='paid').length,partial:bs.filter((x:any)=>x.status==='partial').length});setRecent(p.data||[]);setLoading(false)})()},[]);
 if(loading)return <Loading/>;
 return <section className="content"><div className="hero-strip"><div><span>এই মাস</span><h1>{monthLabel(monthStart())}</h1><p>বিল তৈরি, আদায় ও বকেয়ার সারাংশ</p></div><div className="hero-total"><span>এই মাসে আদায়</span><b>{money(stats.collected)}</b></div></div><div className="stats-grid"><Stat title="মোট গ্রাহক" value={String(stats.customers)} icon="◉"/><Stat title="প্রত্যাশিত বিল" value={money(stats.expected)} icon="৳"/><Stat title="মোট আদায়" value={money(stats.collected)} icon="✓"/><Stat title="বকেয়া" value={money(stats.due)} icon="!"/></div><div className="two-col"><div className="panel"><div className="panel-head"><div><h3>বিল স্ট্যাটাস</h3><span>{stats.paid} paid · {stats.partial} partial</span></div></div><div className="progress-row"><span>Paid</span><b>{stats.paid}</b></div><div className="progress-row"><span>Partial</span><b>{stats.partial}</b></div><div className="progress-row"><span>Due</span><b>{Math.max(0,stats.customers-stats.paid-stats.partial)}</b></div></div><div className="panel"><div className="panel-head"><div><h3>সাম্প্রতিক পেমেন্ট</h3><span>সর্বশেষ ৮টি</span></div></div>{recent.length===0?<Empty text="এখনও কোনো পেমেন্ট নেই"/>:<div className="list">{recent.map(r=><div className="list-row" key={r.id}><div><b>{r.customers?.name||'Customer'}</b><span>{r.receipt_no}</span></div><strong>{money(r.amount)}</strong></div>)}</div>}</div></div></section>
}
function Customers({profile,permissions}:{profile:Profile;permissions:Set<string>}){
 const [rows,setRows]=useState<Customer[]>([]);const [q,setQ]=useState('');const [show,setShow]=useState(false);const [editing,setEditing]=useState<Customer|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('customers').select('*').order('created_at',{ascending:false});if(error)setError(error.message);setRows((data||[]) as Customer[])};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>[x.name,x.customer_code,x.phone,x.connection_no||''].join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function save(data:Partial<Customer>){setBusy(true);setError('');const payload={name:data.name,phone:data.phone,address:data.address||null,connection_no:data.connection_no||null,monthly_amount:Number(data.monthly_amount||150),status:data.status||'active',joined_at:data.joined_at||new Date().toISOString().slice(0,10),photo_url:data.photo_url||null,notes:data.notes||null,user_id:data.user_id||null};let res=editing?await supabase.from('customers').update(payload).eq('id',editing.id):await supabase.from('customers').insert({...payload,customer_code:'CUST-'+Date.now().toString().slice(-5)});if(res.error)setError(res.error.message);else{setShow(false);setEditing(null);await load()}setBusy(false)}
 async function remove(id:string){if(!confirm('এই গ্রাহক মুছে ফেলবেন?'))return;const {error}=await supabase.from('customers').delete().eq('id',id);if(error)setError(error.message);else load()}
 return <section className="content"><div className="toolbar"><input className="search" placeholder="নাম, Customer ID, ফোন বা সংযোগ নম্বর…" value={q} onChange={e=>setQ(e.target.value)}/>{can(profile,permissions,'customers.create')&&<button className="primary" onClick={()=>{setEditing(null);setShow(true)}}>＋ নতুন গ্রাহক</button>}</div>{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Connection</th><th>মাসিক বিল</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><div className="person"><div className="avatar">{c.name.slice(0,1)}</div><div><b>{c.name}</b><span>{c.customer_code}</span></div></div></td><td>{c.phone}</td><td>{c.connection_no||'—'}</td><td>{money(c.monthly_amount)}</td><td><span className={'status '+c.status}>{c.status==='active'?'Active':'Inactive'}</span></td><td className="actions">{can(profile,permissions,'customers.edit')&&<button className="icon-btn" onClick={()=>{setEditing(c);setShow(true)}}>Edit</button>}{can(profile,permissions,'customers.delete')&&<button className="icon-btn danger" onClick={()=>remove(c.id)}>Delete</button>}</td></tr>)}</tbody></table>{filtered.length===0&&<Empty text="কোনো গ্রাহক পাওয়া যায়নি"/></div>{show&&<CustomerModal initial={editing} busy={busy} onClose={()=>{setShow(false);setEditing(null)}} onSave={save}/>}</section>
}
function CustomerModal({initial,busy,onClose,onSave}:{initial:Customer|null;busy:boolean;onClose:()=>void;onSave:(d:Partial<Customer>)=>void}){
 const [form,setForm]=useState<Partial<Customer>>(initial||{name:'',phone:'',address:'',connection_no:'',monthly_amount:150,status:'active',joined_at:new Date().toISOString().slice(0,10),notes:''});
 const set=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 return <Modal title={initial?'গ্রাহক সম্পাদনা':'নতুন গ্রাহক'} onClose={onClose}><div className="form-grid"><label>নাম*<input value={String(form.name||'')} onChange={e=>set('name',e.target.value)} /></label><label>মোবাইল*<input value={String(form.phone||'')} onChange={e=>set('phone',e.target.value)} /></label><label>সংযোগ নম্বর<input value={String(form.connection_no||'')} onChange={e=>set('connection_no',e.target.value)} /></label><label>মাসিক বিল<input type="number" value={Number(form.monthly_amount||0)} onChange={e=>set('monthly_amount',e.target.value)} /></label><label>যোগদানের তারিখ<input type="date" value={String(form.joined_at||'')} onChange={e=>set('joined_at',e.target.value)} /></label><label>Status<select value={String(form.status||'active')} onChange={e=>set('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="wide">ঠিকানা<textarea value={String(form.address||'')} onChange={e=>set('address',e.target.value)}/></label><label className="wide">নোট<textarea value={String(form.notes||'')} onChange={e=>set('notes',e.target.value)}/></label></div><div className="modal-actions"><button onClick={onClose}>বাতিল</button><button className="primary" disabled={busy||!form.name||!form.phone} onClick={()=>onSave(form)}>{busy?'Saving…':'Save'}</button></div></Modal>
}
function Bills({profile,permissions}:{profile:Profile;permissions:Set<string>}){
 const [month,setMonth]=useState(monthStart());const [rows,setRows]=useState<Bill[]>([]);const [q,setQ]=useState('');const [busy,setBusy]=useState(false);const [pay,setPay]=useState<Bill|null>(null);const [msg,setMsg]=useState('');const [error,setError]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('bills').select('*,customers(name,customer_code,phone)').eq('billing_month',month).order('created_at',{ascending:false});if(error)setError(error.message);setRows((data||[]) as Bill[])};
 useEffect(()=>{load()},[month]);
 async function generate(){setBusy(true);setError('');const {data,error}=await supabase.rpc('generate_monthly_bills',{p_month:month});if(error)setError(error.message);else setMsg((data||0)+'টি বিল তৈরি হয়েছে');await load();setBusy(false)}
 async function collect(bill:Bill,amount:number,method:string,notes:string){setBusy(true);setError('');const {error}=await supabase.rpc('record_payment',{p_bill_id:bill.id,p_amount:amount,p_method:method,p_notes:notes||null});if(error)setError(error.message);else{setPay(null);setMsg('পেমেন্ট সফলভাবে সংরক্ষণ হয়েছে');await load()}setBusy(false)}
 const filtered=rows.filter(r=>[r.customer?.name||'',r.customer?.customer_code||'',r.customer?.phone||''].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/><input className="search" placeholder="গ্রাহক খুঁজুন…" value={q} onChange={e=>setQ(e.target.value)}/>{can(profile,permissions,'billing.generate')&&<button className="primary" onClick={generate} disabled={busy}>⚡ {busy?'Processing…':'Generate Bills'}</button>}</div>{msg&&<div className="success">{msg}</div>}{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>গ্রাহক</th><th>Bill</th><th>Paid</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><div className="person"><div className="avatar">{b.customer?.name?.slice(0,1)||'?'}</div><div><b>{b.customer?.name||'—'}</b><span>{b.customer?.customer_code||''}</span></div></div></td><td>{money(b.amount_due)}</td><td>{money(b.amount_paid)}</td><td><b>{money(b.due_amount)}</b></td><td><span className={'status '+b.status}>{b.status}</span></td><td>{b.due_amount>0&&can(profile,permissions,'payments.create')&&<button className="small-primary" onClick={()=>setPay(b)}>পেমেন্ট নিন</button>}</td></tr>)}</tbody></table>{filtered.length===0&&<Empty text="এই মাসের বিল পাওয়া যায়নি। আগে Generate Bills চালান।"/>}</div>{pay&&<PaymentModal bill={pay} busy={busy} onClose={()=>setPay(null)} onSave={(a,m,n)=>collect(pay,a,m,n)}/>}</section>
}
function PaymentModal({bill,busy,onClose,onSave}:{bill:Bill;busy:boolean;onClose:()=>void;onSave:(amount:number,method:string,notes:string)=>void}){
 const [amount,setAmount]=useState(Number(bill.due_amount));const [method,setMethod]=useState('cash');const [notes,setNotes]=useState('');
 return <Modal title="পেমেন্ট গ্রহণ" onClose={onClose}><div className="payment-summary"><span>{bill.customer?.name}</span><b>বকেয়া: {money(bill.due_amount)}</b></div><label>পরিশোধের পরিমাণ<input type="number" min="1" max={bill.due_amount} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>পেমেন্ট মাধ্যম<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="mobile_banking">Mobile Banking</option><option value="bank">Bank</option><option value="other">Other</option></select></label><label>নোট<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="modal-actions"><button onClick={onClose}>বাতিল</button><button className="primary" disabled={busy||amount<=0||amount>bill.due_amount} onClick={()=>onSave(amount,method,notes)}>{busy?'Saving…':'পেমেন্ট সংরক্ষণ'}</button></div></Modal>
}
function Employees({profile,permissions}:{profile:Profile;permissions:Set<string>}){
 const [rows,setRows]=useState<Profile[]>([]);const [permMap,setPermMap]=useState<Record<string,string[]>>({});const [show,setShow]=useState(false);const [form,setForm]=useState({full_name:'',email:'',password:'',phone:''});const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{const {data}=await supabase.from('profiles').select('*').eq('role','employee').order('created_at',{ascending:false});setRows((data||[]) as Profile[]);const {data:p}=await supabase.from('employee_permissions').select('user_id,permission');const map:Record<string,string[]>={};(p||[]).forEach((x:any)=>(map[x.user_id]??=[]).push(x.permission));setPermMap(map)};
 useEffect(()=>{load()},[]);
 async function toggle(uid:string,p:string){const has=(permMap[uid]||[]).includes(p);if(has){await supabase.from('employee_permissions').delete().eq('user_id',uid).eq('permission',p)}else{await supabase.from('employee_permissions').insert({user_id:uid,permission:p})}load()}
 async function create(){setBusy(true);setError('');const {data,error}=await supabase.functions.invoke('admin-create-user',{body:form});if(error)setError(error.message);else if(data?.error)setError(data.error);else{setMsg('Employee account তৈরি হয়েছে');setShow(false);setForm({full_name:'',email:'',password:'',phone:''});load()}setBusy(false)}
 if(!can(profile,permissions,'employees.view'))return <section className="content"><Empty text="এই অংশে আপনার access নেই।"/></section>;
 return <section className="content">{can(profile,permissions,'employees.manage')&&<div className="toolbar"><div></div><button className="primary" onClick={()=>setShow(true)}>＋ Employee Account</button></div>}{msg&&<div className="success">{msg}</div>}{error&&<div className="error">{error}</div>}<div className="employee-grid">{rows.map(e=><div className="panel employee-card" key={e.id}><div className="employee-head"><div className="avatar big">{e.full_name.slice(0,1)||'E'}</div><div><h3>{e.full_name}</h3><span>{e.phone||'No phone'}</span><span className={'status '+(e.is_active?'active':'inactive')}>{e.is_active?'Active':'Inactive'}</span></div></div><div className="perm-grid">{PERMISSIONS.map(p=><label key={p} className="check"><input type="checkbox" checked={(permMap[e.id]||[]).includes(p)} onChange={()=>toggle(e.id,p)}/><span>{LABELS[p]}</span></label>)}</div></div>)}{rows.length===0&&<Empty text="কোনো Employee account নেই।" />}</div>{show&&<Modal title="নতুন Employee" onClose={()=>setShow(false)}><label>নাম<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>ইমেইল<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>মোবাইল<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Temporary Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="modal-actions"><button onClick={()=>setShow(false)}>বাতিল</button><button className="primary" disabled={busy||!form.email||!form.password||!form.full_name} onClick={create}>{busy?'Creating…':'Create Employee'}</button></div></Modal>}</section>
}
function Reports(){
 const [month,setMonth]=useState(monthStart());const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{setLoading(true);const {data}=await supabase.from('bills').select('amount_due,amount_paid,due_amount,status,customers(name,customer_code)').eq('billing_month',month);setRows(data||[]);setLoading(false)})()},[month]);
 const total=rows.reduce((a,x)=>a+Number(x.amount_due),0),paid=rows.reduce((a,x)=>a+Number(x.amount_paid),0),due=rows.reduce((a,x)=>a+Number(x.due_amount),0);
 return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/></div>{loading?<Loading/>:<><div className="stats-grid"><Stat title="Expected" value={money(total)} icon="৳"/><Stat title="Collected" value={money(paid)} icon="✓"/><Stat title="Due" value={money(due)} icon="!"/><Stat title="Customers billed" value={String(rows.length)} icon="◉"/></div><div className="panel table-wrap"><table><thead><tr><th>Customer</th><th>Bill</th><th>Paid</th><th>Due</th><th>Status</th></tr></thead><tbody>{rows.map((x,i)=><tr key={i}><td>{x.customers?.name}<span className="muted">{x.customers?.customer_code}</span></td><td>{money(x.amount_due)}</td><td>{money(x.amount_paid)}</td><td>{money(x.due_amount)}</td><td><span className={'status '+x.status}>{x.status}</span></td></tr>)}</tbody></table></div></>}</section>
}
function SettingsPage({settings,onSaved}:{settings:Settings|null;onSaved:()=>void}){
 const [form,setForm]=useState<Settings>(settings||{id:1,company_name:'আরকি নেটওয়ার্ক',tagline:'মাসিক বিল ব্যবস্থাপনা',monthly_bill:150,currency:'BDT',phone:'',address:'',logo_url:''});const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(settings)setForm(settings)},[settings]);
 async function save(){setBusy(true);const {error}=await supabase.from('settings').upsert(form);setMsg(error?error.message:'সেটিংস সংরক্ষণ হয়েছে');if(!error)onSaved();setBusy(false)}
 return <section className="content"><div className="panel settings"><h3>Business Settings</h3><p className="muted">Monthly Bill পরিবর্তন করলে নতুন customer/bill-এর default amount বদলাবে; পুরোনো bill বদলাবে না।</p><div className="form-grid"><label>Company Name<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>Tagline<input value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><label>Default Monthly Bill<input type="number" value={form.monthly_bill} onChange={e=>setForm({...form,monthly_bill:Number(e.target.value)})}/></label><label>Phone<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="wide">Address<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="wide">Cloudinary Logo URL<input value={form.logo_url||''} onChange={e=>setForm({...form,logo_url:e.target.value})}/></label></div>{msg&&<div className="success">{msg}</div>}<button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save Settings'}</button></div></section>
}
function CustomerPortal({profile,settings,onSignOut}:{profile:Profile;settings:Settings|null;onSignOut:()=>void}){
 const [customer,setCustomer]=useState<Customer|null>(null);const [bills,setBills]=useState<Bill[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:c}=await supabase.from('customers').select('*').eq('user_id',profile.id).maybeSingle();setCustomer(c as Customer);if(c){const {data:b}=await supabase.from('bills').select('*').eq('customer_id',c.id).order('billing_month',{ascending:false});setBills((b||[]) as Bill[])}setLoading(false)})()},[profile.id]);
 if(loading)return <Loading/>;const totalDue=bills.reduce((a,b)=>a+Number(b.due_amount),0);
 return <div className="portal"><header className="portal-head"><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Customer Portal</span></div><button onClick={onSignOut}>লগআউট</button></header><main><div className="customer-hero"><div className="avatar big">{customer?.name?.slice(0,1)||'C'}</div><div><span>Customer ID: {customer?.customer_code||'—'}</span><h1>{customer?.name||profile.full_name}</h1><p>{customer?.phone||profile.phone||''}</p></div></div><div className="stats-grid"><Stat title="মাসিক বিল" value={money(customer?.monthly_amount||0)} icon="৳"/><Stat title="মোট বকেয়া" value={money(totalDue)} icon="!"/><Stat title="মোট মাস" value={String(bills.length)} icon="▤"/></div><div className="panel"><div className="panel-head"><div><h3>Bill History</h3><span>আপনার নিজের billing history</span></div></div><div className="bill-cards">{bills.map(b=><div className="bill-card" key={b.id}><div><b>{monthLabel(b.billing_month)}</b><span>Bill: {money(b.amount_due)}</span></div><div><b>{money(b.amount_paid)}</b><span>Paid</span></div><div><b>{money(b.due_amount)}</b><span>Due</span></div><span className={'status '+b.status}>{b.status}</span></div>)}</div></div></main></div>
}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
function Loading(){return <div className="loading">লোড হচ্ছে…</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}

export default function App(){
 const [session,setSession]=useState<any>(null);const [profile,setProfile]=useState<Profile|null>(null);const [permissions,setPermissions]=useState<Set<string>>(new Set());const [settings,setSettings]=useState<Settings|null>(null);const [page,setPage]=useState('dashboard');const [loading,setLoading]=useState(true);
 async function loadUser(s:any){setSession(s);if(!s){setProfile(null);setPermissions(new Set());setLoading(false);return}const {data:p}=await supabase.from('profiles').select('*').eq('id',s.user.id).single();setProfile(p as Profile);const {data:ps}=await supabase.from('employee_permissions').select('permission').eq('user_id',s.user.id);setPermissions(new Set((ps||[]).map((x:any)=>x.permission)));const {data:st}=await supabase.from('settings').select('*').eq('id',1).single();setSettings(st as Settings);setLoading(false)}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>loadUser(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>loadUser(s));return()=>subscription.unsubscribe()},[]);
 async function signOut(){await supabase.auth.signOut();setPage('dashboard')}
 if(loading)return <Loading/>;if(!session||!profile)return <Login/>;if(profile.role==='customer')return <CustomerPortal profile={profile} settings={settings} onSignOut={signOut}/>;
 return <Shell profile={profile} permissions={permissions} settings={settings} onNavigate={setPage} page={page} onSignOut={signOut}>{page==='dashboard'&&<Dashboard/>}{page==='customers'&&<Customers profile={profile} permissions={permissions}/>} {page==='bills'&&<Bills profile={profile} permissions={permissions}/>} {page==='reports'&&<Reports/>} {page==='employees'&&<Employees profile={profile} permissions={permissions}/>} {page==='settings'&&profile.role==='admin'&&<SettingsPage settings={settings} onSaved={reloadSettings}/>}</Shell>
}
