import {useEffect,useMemo,useState} from 'react';
import {supabase} from './lib/supabase';
import type {Bill,Customer,Payment,Profile,Settings} from './types';

const money=(n:number)=>new Intl.NumberFormat('bn-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(Number(n||0));
const monthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)};
const monthLabel=(s:string)=>new Date(s+'T00:00:00').toLocaleDateString('bn-BD',{month:'long',year:'numeric'});

function Login(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 return <div className="login-page"><div className="login-card"><div className="brand-mark">আরকি</div><h1>আরকি নেটওয়ার্ক</h1><p>মাসিক বিল ম্যানেজমেন্ট সিস্টেম</p><form onSubmit={submit}><label>ইমেইল<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>পাসওয়ার্ড<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'প্রবেশ করা হচ্ছে…':'লগইন'}</button></form></div></div>
}

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<Profile|null>(null); const [settings,setSettings]=useState<Settings|null>(null); const [page,setPage]=useState('dashboard'); const [loading,setLoading]=useState(true);
 useEffect(()=>{let mounted=true;(async()=>{const {data}=await supabase.auth.getSession();if(!mounted)return;setSession(data.session);if(data.session)await loadUser(data.session.user.id);setLoading(false)})();const {data:sub}=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s)await loadUser(s.user.id);else setProfile(null)});return()=>{mounted=false;sub.subscription.unsubscribe()}},[]);
 async function loadUser(id:string){const {data:p}=await supabase.from('profiles').select('*').eq('id',id).single();setProfile(p as Profile);const {data:s}=await supabase.from('settings').select('*').eq('id',1).single();setSettings(s as Settings)}
 async function signOut(){await supabase.auth.signOut();setPage('dashboard')}
 if(loading)return <div className="loading">লোড হচ্ছে…</div>;
 if(!session||!profile)return <Login/>;
 if(profile.role==='customer')return <CustomerPortal profile={profile} settings={settings} onSignOut={signOut}/>;
 return <Shell profile={profile} settings={settings} page={page} onNavigate={setPage} onSignOut={signOut}/>;
}

function Shell({profile,settings,page,onNavigate,onSignOut}:{profile:Profile;settings:Settings|null;page:string;onNavigate:(p:string)=>void;onSignOut:()=>void}){
 const items=[['dashboard','ড্যাশবোর্ড'],['customers','গ্রাহক'],['bills','মাসিক বিল'],['reports','রিপোর্ট'],['employees','কর্মচারী'],['audit','অডিট লগ'],['settings','সেটিংস']];
 return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="logo">আরকি</div><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Billing System</span></div></div><nav>{items.map(x=><button key={x[0]} className={page===x[0]?'nav active':'nav'} onClick={()=>onNavigate(x[0])}>{x[1]}</button>)}</nav><div className="side-bottom"><div className="user-mini"><div className="avatar">{profile.full_name?.slice(0,1)||'U'}</div><div><b>{profile.full_name}</b><span>{profile.role}</span></div></div><button className="nav" onClick={onSignOut}>↪ লগআউট</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{settings?.tagline||'মাসিক বিল ব্যবস্থাপনা'}</span><h2>{items.find(x=>x[0]===page)?.[1]}</h2></div><span className="role-pill">{profile.role}</span></header>{page==='dashboard'&&<Dashboard/>}{page==='customers'&&<Customers/>}{page==='bills'&&<Bills/>}{page==='reports'&&<Reports/>}{page==='employees'&&<Employees/>}{page==='audit'&&<AuditLogs/>}{page==='settings'&&<SettingsPage settings={settings} onSaved={async()=>{const {data}=await supabase.from('settings').select('*').eq('id',1).single();setSettings(data as Settings)}}/>}</main></div>
}

function Dashboard(){
 const [stats,setStats]=useState({customers:0,expected:0,paid:0,due:0}); const [recent,setRecent]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const m=monthStart();const [{count},{data:b},{data:p}]=await Promise.all([supabase.from('customers').select('id',{count:'exact',head:true}),supabase.from('bills').select('amount_due,amount_paid,due_amount').eq('billing_month',m),supabase.from('payments').select('id,amount,receipt_no,customers(name)').order('payment_date',{ascending:false}).limit(8)]);const rows=b||[];setStats({customers:count||0,expected:rows.reduce((a,x)=>a+Number(x.amount_due),0),paid:rows.reduce((a,x)=>a+Number(x.amount_paid),0),due:rows.reduce((a,x)=>a+Number(x.due_amount),0)});setRecent(p||[])})()},[]);
 return <section className="content"><div className="hero-strip"><div><span>এই মাস</span><h1>{monthLabel(monthStart())}</h1><p>বিল তৈরি, আদায় ও বকেয়ার সারাংশ</p></div><div className="hero-total"><span>এই মাসে আদায়</span><b>{money(stats.paid)}</b></div></div><div className="stats-grid"><Stat title="মোট গ্রাহক" value={String(stats.customers)} icon="◉"/><Stat title="প্রত্যাশিত বিল" value={money(stats.expected)} icon="৳"/><Stat title="মোট আদায়" value={money(stats.paid)} icon="✓"/><Stat title="বকেয়া" value={money(stats.due)} icon="!"/></div><div className="panel"><div className="panel-head"><div><h3>সাম্প্রতিক পেমেন্ট</h3><span>সর্বশেষ ৮টি</span></div></div>{recent.length?<div className="list">{recent.map(r=><div className="list-row" key={r.id}><div><b>{r.customers?.name||'Customer'}</b><span>{r.receipt_no}</span></div><strong>{money(r.amount)}</strong></div>)}</div>:<Empty text="এখনও কোনো পেমেন্ট নেই।"/>}</div></section>
}
function Stat({title,value,icon}:{title:string;value:string;icon:string}){return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong></div></div>}
function Customers(){
 const [rows,setRows]=useState<Customer[]>([]);const [q,setQ]=useState('');const [show,setShow]=useState(false);const [form,setForm]=useState<any>({name:'',phone:'',address:'',connection_no:'',monthly_amount:150,status:'active'});const [msg,setMsg]=useState('');const [error,setError]=useState('');
 async function load(){const {data,error}=await supabase.from('customers').select('*').order('created_at',{ascending:false});setRows((data||[]) as Customer[]);if(error)setError(error.message)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>[x.name,x.customer_code,x.phone,x.connection_no||''].join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function save(){setError('');const {error}=await supabase.from('customers').insert({...form,monthly_amount:Number(form.monthly_amount),customer_code:'CUST-'+Date.now().toString().slice(-6)});if(error)setError(error.message);else{setMsg('গ্রাহক যোগ হয়েছে');setShow(false);setForm({name:'',phone:'',address:'',connection_no:'',monthly_amount:150,status:'active'});load()}}
 return <section className="content"><div className="toolbar"><input className="search" placeholder="নাম, ID, ফোন বা সংযোগ নম্বর…" value={q} onChange={e=>setQ(e.target.value)}/><button className="primary" onClick={()=>setShow(true)}>＋ নতুন গ্রাহক</button></div>{msg&&<div className="success">{msg}</div>}{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Connection</th><th>মাসিক বিল</th><th>Status</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.name}</b><span>{c.customer_code}</span></td><td>{c.phone}</td><td>{c.connection_no||'—'}</td><td>{money(c.monthly_amount)}</td><td><span className={'status '+c.status}>{c.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<Empty text="কোনো গ্রাহক পাওয়া যায়নি।"/></div>{show&&<Modal title="নতুন গ্রাহক" onClose={()=>setShow(false)}><div className="form-grid"><label>নাম*<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>মোবাইল*<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>সংযোগ নম্বর<input value={form.connection_no} onChange={e=>setForm({...form,connection_no:e.target.value})}/></label><label>মাসিক বিল<input type="number" value={form.monthly_amount} onChange={e=>setForm({...form,monthly_amount:e.target.value})}/></label><label className="wide">ঠিকানা<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="modal-actions"><button onClick={()=>setShow(false)}>বাতিল</button><button className="primary" disabled={!form.name||!form.phone} onClick={save}>Save</button></div></Modal>}</section>
}
function Bills(){
 const [month,setMonth]=useState(monthStart());const [rows,setRows]=useState<Bill[]>([]);const [msg,setMsg]=useState('');const [error,setError]=useState('');const [pay,setPay]=useState<Bill|null>(null);
 async function load(){const {data,error}=await supabase.from('bills').select('*,customers(name,customer_code,phone)').eq('billing_month',month).order('created_at',{ascending:false});setRows((data||[]) as Bill[]);if(error)setError(error.message)}
 useEffect(()=>{load()},[month]);
 async function generate(){setMsg('');setError('');const {data,error}=await supabase.rpc('generate_monthly_bills',{p_month:month});if(error)setError(error.message);else setMsg(String(data||0)+'টি বিল তৈরি হয়েছে');load()}
 async function collect(amount:number,method:string,notes:string){if(!pay)return;const {error}=await supabase.rpc('record_payment',{p_bill_id:pay.id,p_amount:amount,p_method:method,p_notes:notes||null});if(error)setError(error.message);else{setMsg('পেমেন্ট সফলভাবে সংরক্ষণ হয়েছে');setPay(null);load()}}
 return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/><button className="primary" onClick={generate}>⚡ Generate Bills</button></div>{msg&&<div className="success">{msg}</div>}{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>গ্রাহক</th><th>Bill</th><th>Paid</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><b>{b.customer?.name||'—'}</b><span>{b.customer?.customer_code||''}</span></td><td>{money(b.amount_due)}</td><td>{money(b.amount_paid)}</td><td>{money(b.due_amount)}</td><td>{b.status}</td><td>{Number(b.due_amount)>0&&<button className="small-primary" onClick={()=>setPay(b)}>পেমেন্ট নিন</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="এই মাসে কোনো বিল নেই। Generate Bills চাপুন।"/>}</div>{pay&&<PaymentModal bill={pay} onClose={()=>setPay(null)} onSave={collect}/>}</section>
}
function PaymentModal({bill,onClose,onSave}:{bill:Bill;onClose:()=>void;onSave:(amount:number,method:string,notes:string)=>void}){const [amount,setAmount]=useState(Number(bill.due_amount));const [method,setMethod]=useState('cash');const [notes,setNotes]=useState('');return <Modal title="পেমেন্ট গ্রহণ" onClose={onClose}><p><b>{bill.customer?.name}</b> — বকেয়া {money(bill.due_amount)}</p><label>পরিমাণ<input type="number" min="1" max={bill.due_amount} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>মাধ্যম<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="mobile_banking">Mobile Banking</option><option value="bank">Bank</option><option value="other">Other</option></select></label><label>নোট<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="modal-actions"><button onClick={onClose}>বাতিল</button><button className="primary" disabled={amount<=0||amount>Number(bill.due_amount)} onClick={()=>onSave(amount,method,notes)}>পেমেন্ট সংরক্ষণ</button></div></Modal>}
function Reports(){const [month,setMonth]=useState(monthStart());const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('bills').select('amount_due,amount_paid,due_amount,status,customers(name,customer_code)').eq('billing_month',month).then(({data})=>setRows(data||[]))},[month]);const total=rows.reduce((a,x)=>a+Number(x.amount_due),0),paid=rows.reduce((a,x)=>a+Number(x.amount_paid),0),due=rows.reduce((a,x)=>a+Number(x.due_amount),0);return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/></div><div className="stats-grid"><Stat title="Expected" value={money(total)} icon="৳"/><Stat title="Collected" value={money(paid)} icon="✓"/><Stat title="Due" value={money(due)} icon="!"/><Stat title="Customers billed" value={String(rows.length)} icon="◉"/></div></section>}
function Employees(){const [rows,setRows]=useState<Profile[]>([]);useEffect(()=>{supabase.from('profiles').select('*').eq('role','employee').order('created_at',{ascending:false}).then(({data})=>setRows((data||[]) as Profile[]))},[]);return <section className="content"><div className="panel table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.full_name}</td><td>{x.phone||'—'}</td><td>{x.is_active?'Active':'Inactive'}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="কোনো Employee নেই।"/></div></section>}
function AuditLogs(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('audit_logs').select('id,action,entity_type,details,created_at').order('created_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]))},[]);return <section className="content"><div className="panel table-wrap"><table><thead><tr><th>সময়</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('bn-BD')}</td><td>{x.action}</td><td>{x.entity_type}</td><td><code>{JSON.stringify(x.details)}</code></td></tr>)}</tbody></table>{!rows.length&&<Empty text="কোনো audit log নেই।"/></div></section>}
function SettingsPage({settings,onSaved}:{settings:Settings|null;onSaved:()=>void}){const [form,setForm]=useState<Settings>(settings||{id:1,company_name:'আরকি নেটওয়ার্ক',tagline:'মাসিক বিল ব্যবস্থাপনা',monthly_bill:150,currency:'BDT',phone:'',address:'',logo_url:'',updated_at:''});async function save(){await supabase.from('settings').upsert({...form,id:1});onSaved()}return <section className="content"><div className="panel settings"><h3>Business Settings</h3><div className="form-grid"><label>Company Name<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>Tagline<input value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><label>Default Monthly Bill<input type="number" value={form.monthly_bill} onChange={e=>setForm({...form,monthly_bill:Number(e.target.value)})}/></label><label>Phone<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="wide">Address<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><button className="primary" onClick={save}>Save Settings</button></div></section>}
function CustomerPortal({profile,settings,onSignOut}:{profile:Profile;settings:Settings|null;onSignOut:()=>void}){const [c,setC]=useState<Customer|null>(null);const [bills,setBills]=useState<Bill[]>([]);const [payments,setPayments]=useState<Payment[]>([]);useEffect(()=>{(async()=>{const {data:cust}=await supabase.from('customers').select('*').eq('user_id',profile.id).maybeSingle();setC(cust as Customer);if(cust){const [{data:b},{data:p}]=await Promise.all([supabase.from('bills').select('*').eq('customer_id',cust.id).order('billing_month',{ascending:false}),supabase.from('payments').select('*').eq('customer_id',cust.id).order('payment_date',{ascending:false}).limit(20)]);setBills((b||[]) as Bill[]);setPayments((p||[]) as Payment[])}})()},[profile.id]);const due=bills.reduce((a,b)=>a+Number(b.due_amount),0);return <div className="portal"><header className="portal-head"><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Customer Portal</span></div><button onClick={onSignOut}>লগআউট</button></header><main><div className="customer-hero"><div className="avatar big">{c?.name?.slice(0,1)||'C'}</div><div><span>{c?.customer_code||'—'}</span><h1>{c?.name||profile.full_name}</h1><p>{c?.phone||''}</p></div></div><div className="stats-grid"><Stat title="মাসিক বিল" value={money(c?.monthly_amount||0)} icon="৳"/><Stat title="মোট বকেয়া" value={money(due)} icon="!"/><Stat title="মোট বিল" value={String(bills.length)} icon="▤"/></div><div className="panel"><h3>Bill History</h3>{bills.length?<div className="bill-cards">{bills.map(b=><div className="bill-card" key={b.id}><b>{monthLabel(b.billing_month)}</b><span>Bill {money(b.amount_due)}</span><span>Paid {money(b.amount_paid)}</span><span>Due {money(b.due_amount)}</span><span>{b.status}</span></div>)}</div>:<Empty text="কোনো বিল নেই।"/></div><div className="panel"><h3>Payment History</h3>{payments.length?<div className="list">{payments.map(p=><div className="list-row" key={p.id}><div><b>{p.receipt_no}</b><span>{new Date(p.payment_date).toLocaleString('bn-BD')}</span></div><strong>{money(p.amount)}</strong></div>)}</div>:<Empty text="কোনো পেমেন্ট নেই।"/></div></main></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
export default App;
