import {useEffect,useMemo,useState} from 'react';
import type {FormEvent,ReactNode} from 'react';
import {supabase} from './lib/supabase';
import type {Bill,Customer,Payment,Profile,Settings} from './types';

const money=(n:number)=>new Intl.NumberFormat('bn-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(Number(n||0));
const currentMonth=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)};
const monthName=(s:string)=>new Date(s+'T00:00:00').toLocaleDateString('bn-BD',{month:'long',year:'numeric'});

export default function App(){
 const [session,setSession]=useState<any>(null);const [profile,setProfile]=useState<Profile|null>(null);const [settings,setSettings]=useState<Settings|null>(null);const [page,setPage]=useState('dashboard');const [loading,setLoading]=useState(true);
 async function loadUser(id:string){const [p,s]=await Promise.all([supabase.from('profiles').select('*').eq('id',id).single(),supabase.from('settings').select('*').eq('id',1).single()]);setProfile(p.data as Profile);setSettings(s.data as Settings)}
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session)await loadUser(data.session.user.id);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s)setProfile(null)});return()=>data.subscription.unsubscribe()},[]);
 if(loading)return <div className="loading">লোড হচ্ছে…</div>;
 if(!session||!profile)return <Login/>;
 if(profile.role==='customer')return <CustomerPortal profile={profile} settings={settings}/>;
 async function logout(){await supabase.auth.signOut()}
 return <Shell profile={profile} settings={settings} page={page} setPage={setPage} logout={logout}><Page page={page} settings={settings} onSettings={setSettings}/></Shell>;
}

function Login(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);setBusy(false)}
 return <div className="login-page"><div className="login-card"><div className="brand-mark">আরকি</div><h1>আরকি নেটওয়ার্ক</h1><p>মাসিক বিল ম্যানেজমেন্ট</p><form onSubmit={submit}><label>ইমেইল<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>পাসওয়ার্ড<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'প্রবেশ করা হচ্ছে…':'লগইন'}</button></form></div></div>
}

function Shell({profile,settings,page,setPage,logout,children}:{profile:Profile;settings:Settings|null;page:string;setPage:(p:string)=>void;logout:()=>void;children:ReactNode}){
 const items=[['dashboard','ড্যাশবোর্ড'],['customers','গ্রাহক'],['bills','মাসিক বিল'],['reports','রিপোর্ট'],['employees','কর্মচারী'],['audit','অডিট লগ'],['settings','সেটিংস']];
 return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><div className="logo">আরকি</div><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Billing System</span></div></div><nav>{items.map(([id,label])=><button key={id} className={page===id?'nav active':'nav'} onClick={()=>setPage(id)}>{label}</button>)}</nav><div className="side-bottom"><div className="user-mini"><div className="avatar">{profile.full_name?.slice(0,1)||'U'}</div><div><b>{profile.full_name}</b><span>{profile.role}</span></div></div><button className="nav" onClick={logout}>↪ লগআউট</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{settings?.tagline||'মাসিক বিল ব্যবস্থাপনা'}</span><h2>{items.find(x=>x[0]===page)?.[1]||'ড্যাশবোর্ড'}</h2></div><span className="role-pill">{profile.role}</span></header>{children}</main></div>
}

function Page({page,settings,onSettings}:{page:string;settings:Settings|null;onSettings:(s:Settings)=>void}){
 if(page==='customers')return <Customers/>;
 if(page==='bills')return <Bills/>;
 if(page==='reports')return <Reports/>;
 if(page==='employees')return <Employees/>;
 if(page==='audit')return <AuditLogs/>;
 if(page==='settings')return <SettingsPage settings={settings} onSaved={onSettings}/>;
 return <Dashboard/>;
}

function Dashboard(){
 const [customers,setCustomers]=useState(0);const [expected,setExpected]=useState(0);const [paid,setPaid]=useState(0);const [due,setDue]=useState(0);const [recent,setRecent]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const m=currentMonth();const a=await supabase.from('customers').select('id',{count:'exact',head:true});const b=await supabase.from('bills').select('amount_due,amount_paid,due_amount').eq('billing_month',m);const p=await supabase.from('payments').select('id,amount,receipt_no,customers(name)').order('payment_date',{ascending:false}).limit(8);setCustomers(a.count||0);setExpected((b.data||[]).reduce((x,r)=>x+Number(r.amount_due),0));setPaid((b.data||[]).reduce((x,r)=>x+Number(r.amount_paid),0));setDue((b.data||[]).reduce((x,r)=>x+Number(r.due_amount),0));setRecent(p.data||[])})()},[]);
 return <section className="content"><div className="hero-strip"><div><span>এই মাস</span><h1>{monthName(currentMonth())}</h1><p>বিল, আদায় ও বকেয়ার সারাংশ</p></div><div className="hero-total"><span>আদায়</span><b>{money(paid)}</b></div></div><div className="stats-grid"><Stat title="মোট গ্রাহক" value={String(customers)} icon="◉"/><Stat title="প্রত্যাশিত বিল" value={money(expected)} icon="৳"/><Stat title="মোট আদায়" value={money(paid)} icon="✓"/><Stat title="বকেয়া" value={money(due)} icon="!"/></div><div className="panel"><h3>সাম্প্রতিক পেমেন্ট</h3>{recent.length?<div className="list">{recent.map(r=><div className="list-row" key={r.id}><div><b>{r.customers?.name||'Customer'}</b><span>{r.receipt_no}</span></div><strong>{money(r.amount)}</strong></div>)}</div>:<Empty text="এখনও কোনো পেমেন্ট নেই।"/>}</div></section>
}
function Stat({title,value,icon}:{title:string;value:string;icon:string}){return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong></div></div>}

function Customers(){
 const [rows,setRows]=useState<Customer[]>([]);const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [error,setError]=useState('');
 async function load(){const r=await supabase.from('customers').select('*').order('created_at',{ascending:false});setRows((r.data||[]) as Customer[]);if(r.error)setError(r.error.message)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>[x.name,x.customer_code,x.phone,x.connection_no||''].join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <section className="content"><div className="toolbar"><input className="search" placeholder="নাম, ID, ফোন বা সংযোগ…" value={q} onChange={e=>setQ(e.target.value)}/><button className="primary" onClick={()=>setOpen(true)}>＋ নতুন গ্রাহক</button></div>{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>গ্রাহক</th><th>ফোন</th><th>সংযোগ</th><th>মাসিক বিল</th><th>স্ট্যাটাস</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.name}</b><span>{c.customer_code}</span></td><td>{c.phone}</td><td>{c.connection_no||'—'}</td><td>{money(c.monthly_amount)}</td><td>{c.status}</td></tr>)}</tbody></table>{!filtered.length&&<Empty text="কোনো গ্রাহক নেই।"/></div>{open&&<CustomerForm close={()=>setOpen(false)} saved={()=>{setOpen(false);load()}}/>}</section>
}
function CustomerForm({close,saved}:{close:()=>void;saved:()=>void}){
 const [f,setF]=useState({name:'',phone:'',address:'',connection_no:'',monthly_amount:150});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 async function save(){setBusy(true);const {error}=await supabase.from('customers').insert({name:f.name,phone:f.phone,address:f.address||null,connection_no:f.connection_no||null,monthly_amount:Number(f.monthly_amount)||150,status:'active',customer_code:'CUST-'+Date.now().toString().slice(-6)});if(error)setError(error.message);else saved();setBusy(false)}
 return <Modal title="নতুন গ্রাহক" onClose={close}><div className="form-grid"><label>নাম*<input value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>মোবাইল*<input value={f.phone} onChange={e=>set('phone',e.target.value)}/></label><label>সংযোগ নম্বর<input value={f.connection_no} onChange={e=>set('connection_no',e.target.value)}/></label><label>মাসিক বিল<input type="number" value={f.monthly_amount} onChange={e=>set('monthly_amount',e.target.value)}/></label><label className="wide">ঠিকানা<textarea value={f.address} onChange={e=>set('address',e.target.value)}/></label></div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button onClick={close}>বাতিল</button><button className="primary" disabled={busy||!f.name||!f.phone} onClick={save}>সংরক্ষণ</button></div></Modal>
}

function Bills(){
 const [month,setMonth]=useState(currentMonth());const [rows,setRows]=useState<Bill[]>([]);const [error,setError]=useState('');const [pay,setPay]=useState<Bill|null>(null);const [message,setMessage]=useState('');
 async function load(){const r=await supabase.from('bills').select('*,customers(name,customer_code,phone)').eq('billing_month',month).order('created_at',{ascending:false});setRows((r.data||[]) as Bill[]);if(r.error)setError(r.error.message)}
 useEffect(()=>{load()},[month]);
 async function generate(){setError('');const r=await supabase.rpc('generate_monthly_bills',{p_month:month});if(r.error)setError(r.error.message);else setMessage(String(r.data||0)+'টি বিল তৈরি হয়েছে');load()}
 async function collect(amount:number,method:string,notes:string){if(!pay)return;const r=await supabase.rpc('record_payment',{p_bill_id:pay.id,p_amount:amount,p_method:method,p_notes:notes||null});if(r.error)setError(r.error.message);else{setMessage('পেমেন্ট সংরক্ষণ হয়েছে');setPay(null);load()}}
 return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/><button className="primary" onClick={generate}>⚡ Generate Bills</button></div>{message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>গ্রাহক</th><th>বিল</th><th>পরিশোধ</th><th>বকেয়া</th><th>স্ট্যাটাস</th><th></th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><b>{b.customer?.name||'—'}</b><span>{b.customer?.customer_code||''}</span></td><td>{money(b.amount_due)}</td><td>{money(b.amount_paid)}</td><td>{money(b.due_amount)}</td><td>{b.status}</td><td>{Number(b.due_amount)>0&&<button className="small-primary" onClick={()=>setPay(b)}>পেমেন্ট</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="এই মাসে বিল নেই। Generate Bills চাপুন।"/></div>{pay&&<PaymentForm bill={pay} close={()=>setPay(null)} saved={collect}/>}</section>
}
function PaymentForm({bill,close,saved}:{bill:Bill;close:()=>void;saved:(a:number,m:string,n:string)=>void}){const [amount,setAmount]=useState(Number(bill.due_amount));const [method,setMethod]=useState('cash');const [notes,setNotes]=useState('');return <Modal title="পেমেন্ট গ্রহণ" onClose={close}><p><b>{bill.customer?.name}</b> — বকেয়া {money(bill.due_amount)}</p><label>পরিমাণ<input type="number" min="1" max={Number(bill.due_amount)} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>মাধ্যম<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="mobile_banking">Mobile Banking</option><option value="bank">Bank</option><option value="other">Other</option></select></label><label>নোট<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="modal-actions"><button onClick={close}>বাতিল</button><button className="primary" disabled={amount<=0||amount>Number(bill.due_amount)} onClick={()=>saved(amount,method,notes)}>সংরক্ষণ</button></div></Modal>}

function Reports(){const [month,setMonth]=useState(currentMonth());const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('bills').select('amount_due,amount_paid,due_amount,status,customers(name,customer_code)').eq('billing_month',month).then(r=>setRows(r.data||[]))},[month]);const total=rows.reduce((a,x)=>a+Number(x.amount_due),0);const paid=rows.reduce((a,x)=>a+Number(x.amount_paid),0);const due=rows.reduce((a,x)=>a+Number(x.due_amount),0);return <section className="content"><div className="toolbar"><input type="month" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+'-01')}/></div><div className="stats-grid"><Stat title="Expected" value={money(total)} icon="৳"/><Stat title="Collected" value={money(paid)} icon="✓"/><Stat title="Due" value={money(due)} icon="!"/><Stat title="Bills" value={String(rows.length)} icon="◉"/></div></section>}
function Employees(){const [rows,setRows]=useState<Profile[]>([]);useEffect(()=>{supabase.from('profiles').select('*').eq('role','employee').order('created_at',{ascending:false}).then(r=>setRows((r.data||[]) as Profile[]))},[]);return <section className="content"><div className="panel table-wrap"><table><thead><tr><th>নাম</th><th>ফোন</th><th>স্ট্যাটাস</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.full_name}</td><td>{x.phone||'—'}</td><td>{x.is_active?'Active':'Inactive'}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="কোনো Employee নেই।"/></div></section>}
function AuditLogs(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('audit_logs').select('id,action,entity_type,details,created_at').order('created_at',{ascending:false}).limit(100).then(r=>setRows(r.data||[]))},[]);return <section className="content"><div className="panel table-wrap"><table><thead><tr><th>সময়</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('bn-BD')}</td><td>{x.action}</td><td>{x.entity_type}</td><td><code>{JSON.stringify(x.details)}</code></td></tr>)}</tbody></table>{!rows.length&&<Empty text="কোনো audit log নেই।"/></div></section>}
function SettingsPage({settings,onSaved}:{settings:Settings|null;onSaved:(s:Settings)=>void}){const [f,setF]=useState<Settings>(settings||{id:1,company_name:'আরকি নেটওয়ার্ক',tagline:'মাসিক বিল ব্যবস্থাপনা',monthly_bill:150,currency:'BDT',phone:'',address:'',logo_url:'',updated_at:''});useEffect(()=>{if(settings)setF(settings)},[settings]);async function save(){const r=await supabase.from('settings').upsert({...f,id:1}).select().single();if(r.data)onSaved(r.data as Settings)}return <section className="content"><div className="panel settings"><h3>Business Settings</h3><div className="form-grid"><label>Company Name<input value={f.company_name} onChange={e=>setF({...f,company_name:e.target.value})}/></label><label>Tagline<input value={f.tagline} onChange={e=>setF({...f,tagline:e.target.value})}/></label><label>Default Monthly Bill<input type="number" value={f.monthly_bill} onChange={e=>setF({...f,monthly_bill:Number(e.target.value)})}/></label><label>Phone<input value={f.phone||''} onChange={e=>setF({...f,phone:e.target.value})}/></label><label className="wide">Address<input value={f.address||''} onChange={e=>setF({...f,address:e.target.value})}/></label></div><button className="primary" onClick={save}>সেটিংস সংরক্ষণ</button></div></section>}
function CustomerPortal({profile,settings}:{profile:Profile;settings:Settings|null}){const [c,setC]=useState<Customer|null>(null);const [bills,setBills]=useState<Bill[]>([]);const [payments,setPayments]=useState<Payment[]>([]);useEffect(()=>{(async()=>{const r=await supabase.from('customers').select('*').eq('user_id',profile.id).maybeSingle();setC(r.data as Customer);if(r.data){const [b,p]=await Promise.all([supabase.from('bills').select('*').eq('customer_id',r.data.id).order('billing_month',{ascending:false}),supabase.from('payments').select('*').eq('customer_id',r.data.id).order('payment_date',{ascending:false}).limit(20)]);setBills((b.data||[]) as Bill[]);setPayments((p.data||[]) as Payment[])}})()},[profile.id]);const due=bills.reduce((a,b)=>a+Number(b.due_amount),0);return <div className="portal"><header className="portal-head"><div><b>{settings?.company_name||'আরকি নেটওয়ার্ক'}</b><span>Customer Portal</span></div><button onClick={()=>supabase.auth.signOut()}>লগআউট</button></header><main><div className="customer-hero"><div className="avatar big">{c?.name?.slice(0,1)||'C'}</div><div><span>{c?.customer_code||'—'}</span><h1>{c?.name||profile.full_name}</h1><p>{c?.phone||''}</p></div></div><div className="stats-grid"><Stat title="মাসিক বিল" value={money(c?.monthly_amount||0)} icon="৳"/><Stat title="মোট বকেয়া" value={money(due)} icon="!"/><Stat title="মোট বিল" value={String(bills.length)} icon="▤"/></div><div className="panel"><h3>Bill History</h3>{bills.length?<div className="bill-cards">{bills.map(b=><div className="bill-card" key={b.id}><b>{monthName(b.billing_month)}</b><span>Bill {money(b.amount_due)}</span><span>Paid {money(b.amount_paid)}</span><span>Due {money(b.due_amount)}</span><span>{b.status}</span></div>)}</div>:<Empty text="কোনো বিল নেই।"/></div><div className="panel"><h3>Payment History</h3>{payments.length?<div className="list">{payments.map(p=><div className="list-row" key={p.id}><div><b>{p.receipt_no}</b><span>{new Date(p.payment_date).toLocaleString('bn-BD')}</span></div><strong>{money(p.amount)}</strong></div>)}</div>:<Empty text="কোনো পেমেন্ট নেই।"/></div></main></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
